[project]
name = "pydevcon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "netmiko>=4.5.0",
    "xmltodict>=0.14.2",
]
